---
- name: Update inventory of LXC
  hosts: proxmox_all_lxc
  gather_facts: false
  remote_user: ansible
  become: true
  vars:
      inventory_file: "/app/ansible/inventory/lxc_inventory"
  tasks:
    - name: Get lxc IP by its vmid
      shell: lxc-info -n "{{ proxmox_vmid }}" -iH
      register: ip
      delegate_to: 192.168.15.100

    - name:  update the inventory file
      lineinfile:
        dest: "{{ inventory_file }}"
        line:  "{{ proxmox_hostname }} ansible_host={{ ip.stdout }} ansible_port=22"
        create: yes
        regexp: "{{ proxmox_hostname }}"
      delegate_to: localhost
