plugin: community.general.proxmox
url: https://192.168.15.100:8006
user: ansible_user@pve
password: Pa$$w0rd
validate_certs: false
want_facts: true
groups:
  template: "'template' in (proxmox_tags_parsed|list)"
keyed_groups:
  - key: proxmox_tags_parsed
    separator: "_"
    prefix: grp
compose:
  ansible_port: 22
#  ansible_host: proxmox_net0.ip | default(proxmox_agent_interfaces[1].ip-addresses[0]) | ipaddr('address')
  ansible_host: proxmox_net0.ip | ipaddr('address')
want_proxmox_nodes_ansible_host: false

