---
- name: Setup Photoblog on Ubuntu Server
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name: "{{ item }}"
        update_cache: true
        cache_valid_time: 3600
        state: present
      loop: "{{ packages_pentest }}"

    - name: Clone Photoblog repository
      git:
        repo: "{{ photoblog_repo }}"
        dest: "{{ photoblog_path }}"
        force: yes

    - name: Allow root login via SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin yes'

    - name: Create SSH authorized_keys directory
      file:
        path: /root/.ssh
        state: directory
        mode: '0700'

    - name: Add SSH key for root
      lineinfile:
        path: /root/.ssh/authorized_keys
        create: yes
        line: "{{ ssh_key }}"

    - name: Enable PHP error display
      lineinfile:
        path: /etc/php/7.4/apache2/php.ini
        regexp: '^display_errors = Off'
        line: 'display_errors = On'

    - name: Comment out disable_function in PHP config
      lineinfile:
        path: /etc/php/7.4/apache2/php.ini
        regexp: '^disable_function'
        line: '#disable_function'

    - name: Create Apache Photoblog configuration
      copy:
        dest: /etc/apache2/sites-available/photoblog.conf
        content: |
          <VirtualHost *:80>
              ServerAdmin webmaster@localhost
              DocumentRoot /var/www/photoblog
              ErrorLog ${APACHE_LOG_DIR}/error.log
              CustomLog ${APACHE_LOG_DIR}/access.log combined
              Options +Indexes
          </VirtualHost>

    - name: Load Photoblog SQL into MySQL
      mysql_db:
        state: import
        target: "{{ photoblog_path }}/photoblog.sql"

    - name: Enable Photoblog site
      file:
        src: /etc/apache2/sites-available/photoblog.conf
        dest: /etc/apache2/sites-enabled/photoblog.conf
        state: link

    - name: Disable default Apache site
      file:
        path: /etc/apache2/sites-enabled/000-default.conf
        state: absent

    - name: Enable Apache autoindex module
      apache2_module:
        name: autoindex
        state: present

    - name: Restart Apache
      service:
        name: apache2
        state: restarted

    - name: Restart SSH
      service:
        name: ssh
        state: restarted