- name: Create the prive network
  hosts: localhost
  gather_facts: false
  become: true
  vars:
    - lxc_hostname: "student-{{ student }}-kali"
    - vmbr: "vmbr{{ student }}"
  pre_tasks:
    - include_vars:
        file: vars.yml
  tasks:
    - name: Ensure vmbr1 bridge configuration exists in /etc/network/interfaces
      ansible.builtin.lineinfile:
      path: /home/ansible/test.int
      line: "auto vmbr1\niface vmbr1 inet manual\n\tbridge_ports none\n\tbridge_stp off\n\tbridge_fd 0"
      state: present