---
- name: Deploy pentester LXC
  hosts: pve
  gather_facts: false
  become: true
  vars:
    - lxc_hostname: "student-{{ student }}-pentest"
    - vmbr: "vmbr{{ student }}"
  pre_tasks:
    - include_vars:
        file: vars.yml
        
    - name: Stop container
      community.general.proxmox:
        vmid: "{{ pentest_template_id }}"
        api_user: "{{ pve_user }}"
        api_password: "{{ pve_pass }}"
        api_host: "{{ pve_host }}"
        state: stopped
  tasks:
    - name: Clone the LXC
      command: "pct clone {{ pentest_template_id }} {{ pentest_student_vmid }} --full --storage datastore-1 --hostname {{ lxc_hostname }}"


    - name: Configure the interfaces
      command: "pct set {{ pentest_student_vmid }} -net0 name=eth0,bridge=vmbr0,ip=dhcp -net1 name=eth1,bridge={{ vmbr }},ip={{ pentest_ip }}"

    - name: Start the container
      community.general.proxmox:
        vmid: "{{ pentest_student_vmid }}"
        api_user: "{{ pve_user }}"
        api_password: "{{ pve_pass }}"
        api_host: "{{ pve_host }}"
        state: started


  ## Create new interface