- name: Deploy attacker
  hosts: pve
  gather_facts: false
  become: true
  vars:
    - lxc_hostname: "student-{{ student }}-kali"
    - vmbr: "vmbr{{ student }}"
  pre_tasks:
    - include_vars:
        file: vars.yml
    - name: Stop container
      community.general.proxmox:
        vmid: "{{ kali_template_id }}"
        api_user: "{{ pve_user }}"
        api_password: "{{ pve_pass }}"
        api_host: "{{ pve_host }}"
        state: stopped
  tasks:
    - name: Clone the LXC
      command: "pct clone {{ kali_template_id }} {{ kali_student_vmid }} --full --storage datastore-1 --hostname {{ lxc_hostname }}"


    - name: Configure the interfaces
      command: "pct set {{ kali_student_vmid }} -net0 name=eth0,bridge=vmbr0,ip=dhcp -net1 name=eth1,bridge={{ vmbr }},ip={{ kali_ip }}"

    - name: Start the container
      community.general.proxmox:
        vmid: "{{ kali_student_vmid }}"
        api_user: "{{ pve_user }}"
        api_password: "{{ pve_pass }}"
        api_host: "{{ pve_host }}"
        state: started

    - name : Reset IP
      command: pct exec "{{ kali_student_vmid }}" -- bash -c "dhclient -r && dhclient"

    - name: Get lxc IP by its vmid
      shell: lxc-info -n "{{ kali_student_vmid }}" -iH | grep "^192.168"
      register: ipconf

    - command: mkdir -p "{{ config_file_location }}"
      delegate_to: localhost

    - name: Writing config file
      ansible.builtin.template:
        src: templates/ipconfig.j2
        dest: "{{ config_file_location }}/{{ lxc_hostname }}"
      delegate_to: localhost