---
- name: Deploy pentester LXC
  hosts: pve
  gather_facts: false
  become: true
  vars:
    - lxc_hostname: "student-{{ student }}-pentest"
  pre_tasks:
    - include_vars:
        file: vars.yml
  tasks:

  ## Configure static IP (add new interface + delete old one)

  ## Clone LXC container

  ## Configure network