---
- name: Deploy pentester LXC
  hosts: pve
  gather_facts: false
  become: true
  vars:
    - lxc_hostname: "student-{{ student }}-pentest"
    - vmbr: "vmbr{{ student }}"
  pre_tasks:
    - include_vars:
        file: vars.yml
        
    - name: Stop container
      community.general.proxmox:
        vmid: "{{ pentest_template_id }}"
        api_user: "{{ pve_user }}"
        api_password: "{{ pve_pass }}"
        api_host: "{{ pve_host }}"
        state: stopped
  tasks:
    - name: Create a full clone of the container
      community.general.proxmox:
        vmid: "{{ pentest_student_vmid }}"
        api_user: "{{ pve_user }}"
        api_password: "{{ pve_pass }}"
        api_host: "{{ pve_host }}"
        node: vir2-pve-01
        clone: "{{ pentest_template_id }}"
        clone_type: full
        storage: datastore-1
        hostname: "{{ lxc_hostname }}"
        state: present
        tags:
          - attacker

    - name: Configure the LXC container network interface
      community.general.proxmox_kvm:
        api_user: "{{ pve_user }}"
        api_password: "{{ pve_pass }}"
        api_host: "{{ pve_host }}"
        vmid: "{{ lxc_vmid }}"
        net: |
          net1: name=eth0,bridge={{ vmbr }},ip={{ pentest_ip }},type=veth

    - name: Start the container
      community.general.proxmox:
        vmid: "{{ pentest_student_vmid }}"
        api_user: "{{ pve_user }}"
        api_password: "{{ pve_pass }}"
        api_host: "{{ pve_host }}"
        state: started


  ## Create new interface