## Update/Configure the kali template
---
- name: Starting container
  hosts: pve
  pre_tasks:
    - include_vars:
        file: vars.yml
  tasks:
    - name: Start container 
      community.general.proxmox:
        vmid: "{{ kali_template_id }}"
        api_user: "{{ pve_user }}"
        api_password: "{{ pve_pass }}"
        api_host: "{{ pve_host }}"
        state: started

- name: Update kali-template
  hosts: kali-template
  gather_facts: false
  become: true
  pre_tasks:
    - include_vars:
        file: vars.yml
  tasks:
    - name: Install new softwares
      apt:
        name: "{{ item }}"
        update_cache: true
        cache_valid_time: 3600
        state: present
      loop: "{{ packages_kali }}"

    - name: Enable ssh root login
      ansible.builtin.lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: "PermitRootLogin yes"

- name: Stopping the template
  hosts: pve
  gather_facts: false
  become: true
  tasks:
    - name: Stop container
      community.general.proxmox:
        vmid: "{{ kali_template_id }}"
        api_user: "{{ pve_user }}"
        api_password: "{{ pve_pass }}"
        api_host: "{{ pve_host }}"
        state: stopped