- name: Delete all infras
  hosts: pve
  gather_facts: false
  become: true
  tasks:
    - name: Get list of  LXC containers with VMIDs starting with 2XX or 3XX
      shell: pct list | grep '^[23][0-9][0-9]' | awk '$2 == "stopped" {print $1}'
      register: lxc

    - name: LXC VMIDs
      debug:
        msg: "{{ lxc.stdout_lines }}"

    - name: Stopping and deleting infras
      shell: pct destroy {{ item }}
      with_items: "{{ lxc.stdout_lines }}"